all: main_proj.cpp Info.cpp Net.cpp Tree.cpp Node.cpp Dimension.cpp include.h my_executable
	g++ main_proj.cpp Info.cpp Net.cpp Tree.cpp Node.cpp Dimension.cpp -o my_executable
	@echo 'Compilation Done!...'
	
clean: 
	@rm a.out
	@echo 'executable file deleted!..'
